#!/bin/bash

messageSleep="0.2"
renderSleep="0.1"

archPath="/data/local/container/arch"
tmpPath="/data/local/container/tmp"
managerPath="$HOME/.archlinux-manager"

arch_logo() {
    printf "\e[36m                  ▄
                 ▄█▄
                ▄███▄
               ▄█████▄
              ▄███████▄
             ▄ ▀▀██████▄
            ▄██▄▄ ▀█████▄
           ▄█████████████▄
          ▄███████████████▄
         ▄█████████████████▄
        ▄███████████████████▄
       ▄█████████▀▀▀▀████████▄
      ▄████████▀      ▀███████▄
     ▄█████████        ████▀▀██▄
    ▄██████████        █████▄▄▄
   ▄██████████▀        ▀█████████▄
  ▄██████▀▀▀              ▀▀██████▄
 ▄███▀▀                       ▀▀███▄
▄▀▀                               ▀▀▄\e[0m\n\n"
}

warning() {
    sleep "$messageSleep"
    printf "[\e[0;33mWARNING\e[0m] - %s\n" "$1"
}

success() {
    sleep "$messageSleep"
    printf "[\e[0;32mSUCCESS\e[0m] - %s\n" "$1"
}

info() {
    sleep "$messageSleep"
    printf "[\e[0;34mINFO\e[0m] - %s\n" "$1"
}

error() {
    sleep "$messageSleep"
    printf "[\e[0;31mERROR\e[0m] - %s\n" "$1" >&2
}

good_option() {
    sleep "$messageSleep"
    [ "$2" == "1" ] && local color="34" || local color="37"
    printf "\e[0;%sm%s\e[0m\n" "$color" "$1"
}

bad_option() {
    sleep "$messageSleep"
    [ "$2" == "1" ] && local color="31" || local color="37"
    printf "\e[0;%sm%s\e[0m\n" "$color" "$1"
}

get_arg_no_check() {
    local arg="$1"
    local argName="$2"

    if [[ -z "$arg" || "$arg" =~ ^-- ]]; then
        echo ""
        return
    fi
    echo "$arg"
}

is_root() {
    if ! su -c "test -f \"/bin/su\"" > /dev/null 2>&1; then
        echo "2"
        return 2
    fi
    if ! su -c "exit" > /dev/null 2>&1; then
        echo "1"
        return 1
    fi
    echo "0"
    return 0
}

verify_root_access() {
    local attempts=1
    while (( attempts <= 2 )); do
        case "$(is_root)" in
            1)
                error "Can't not acceess superuser permission"
                info "Root your device with magisk or kernelsu based root provider and grant superuser permission"
                exit 1
            ;;
            2)
                error "Can't not find /bin/su"
                warning "Your root provider does not support /bin/su"
                info "Trying to create link between /bin/su -> /bin/sh"
                su -c "(
                    set -e
                    mount -o remount,rw /system
                    ln -s /system/bin/sh /system/bin/su
                    mount -o remount,ro /system
                )" > /dev/null 2>&1 || {
                    error "Can't create link"
                    info "Please change your root provider or download and install /bin/su"
                    if [ $attempts -eq 2 ]; then
                        warning "You might also run user build system which is not supported"
                        exit 1
                    fi
                }
                success "Link between /bin/su -> /bin/sh was successfully created"
            ;;
        esac
        attempts=$((attempts + 1))
    done
}

setup_enviroment() {
    info "Installing needed packages"
    (
        set -e
        pkg update
        pkg upgrade -y
        pkg install root-repo -y
        pkg install busybox -y
        pkg install tar -y
    ) || {
        error "Failed to install some packages"
        exit 1
    }
    success "Packages were successfully installed"
}

is_enviroment_setup() {
    (
        set -e
        pkg list-installed | grep "busybox"
        pkg list-installed | grep "tar"
        pkg list-installed | grep "root-repo"
    ) > /dev/null 2>&1 || {
        return 1
    }
    return 0
}

detect_input() {
    read -rsn1 key 2>/dev/null || (echo "0" && return 0 )
    [ -z "$key" ] && (echo "1" && return 0 )
    if [ "$key" = $'\e' ]; then
        read -rsn2 next 2>/dev/null || (echo "1" && return 0 )
        [ "$key$next" = $'\e[A' ] && (echo "2" && return 0 )
        [ "$key$next" = $'\e[B' ] && (echo "3" && return 0 )
    fi
}

render_menu() {
    local selected=1
    local input="0"
    while true; do
        clear
        arch_logo
        good_option "Manage" [[ $selected -eq 1 ]]
        good_option "Login" [[ $selected -eq 2 ]]
        good_option "Shutdown" [[ $selected -eq 3 ]]
        good_option "Install" [[ $selected -eq 4 ]]
        bad_option "Uninstall" [[ $selected -eq 5 ]]
        bad_option "Reinstall" [[ $selected -eq 6 ]]
        bad_option "Remove All Files" [[ $selected -eq 7 ]]
        bad_option "Remove ZIP" [[ $selected -eq 8 ]]
        while true; do
            input=$(detect_input)
            sleep "$renderSleep"
        done
        case "$input" in
            1)
                case "$selected" in
                    1)

                    ;;
                    2)

                    ;;
                    3)

                    ;;
                    4)

                    ;;
                    5)

                    ;;
                    6)

                    ;;
                    7)

                    ;;
                    8)

                    ;;
                esac
            ;;
            2)
                selected=$((selected + 1))
                [ $selected -gt 8 ] && selected=8
            ;;
            3)
                selected=$((selected - 1))
                [ $selected -lt 1 ] && selected=1
            ;;
        esac
    done
}

verify_root_access

if ! is_enviroment_setup; then
    setup_enviroment
fi

render_menu